### ISSUE TITLE
password reset causes internal error

### ISSUE THREAD

**Issue by adamamyl** [supdegrave/meteor-evm#41]
Steps to reproduce:

 - ensure not logged in
 - hit forgot password link on homepage
 - enter valid users' email address
 - hit enter
 - receive error message.

**Comment by MonkeyDo** [comment]
Debug on server console:

Exception while invoking method 'forgotPassword' TypeError: Cannot call method 'subject' of undefined
     at Object.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:400:1)
     at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:358:1)
     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
     at packages/ddp/livedata_server.js:648:1
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at packages/ddp/livedata_server.js:647:1
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1
